name: Create EC2 Instance

on:
  push:
    branches:
      - testingbranch4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID }}
          aws-secret-access-key: ${{ secrets.KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        run: |
         instance_id=$(aws ec2 run-instances \
            --image-id ami-12345678 \
            --instance-type t2.micro \
            --key-name your-key-pair \
            --security-group-ids sg-12345678 \
            --subnet-id subnet-12345678 \
            --query 'Instances[0].InstanceId' --output text)

          aws ec2 create-tags --resources $instance_id --tags Key=Name,Value=MyInstanceName
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.KEY }}
