name: Create EC2 Instance

on:
  push:
    branches:
      - testingbranch4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID }}
          aws-secret-access-key: ${{ secrets.KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        run: |
          instance_id=$(aws ec2 run-instances \
            --image-id ami-005f8adf84f8c5057 \
            --instance-type t2.micro \
            --key-name ec2Win2022 \
            --security-group-ids sg-0de8cf629b11c00e5 \
            --subnet-id subnet-03be3039f3ef0ad2c \
            --query 'Instances[0].InstanceId' --output text)
          echo "EC2 instance ID: $instance_id"

          while [[ "$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[0].Instances[0].State.Name' --output text)" != "running" ]]; do
              echo "Waiting for EC2 instance to be in running state..."
              sleep 100
          done
          
          echo "EC2 instance is now in a running state."

      - name: Install Chocolatey and Git
        run: |
          # Install Chocolatey
          Set-ExecutionPolicy Bypass -Scope Process -Force; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
          
          # Install Git using Chocolatey
          choco install git -y
            
