name: Running .NET App

on:
  push:
    branches: [testingbranch4]

jobs:
  build:
    name: Build and Push Image
    runs-on: Windows

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID }}
          aws-secret-access-key: ${{ secrets.KEY }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: windowscontainer
          IMAGE_TAG: winTestImage
        run: |
          docker build -t aspnet4.8 .

          docker tag aspnet4.8 481331750683.dkr.ecr.us-east-1.amazonaws.com/baseimg:aspnet4.8

          docker push 481331750683.dkr.ecr.us-east-1.amazonaws.com/baseimg:aspnet4.8

      - name: Tag the Docker Image Locally
        run: docker tag 481331750683.dkr.ecr.us-east-1.amazonaws.com/baseimg:aspnet4.8 local:aspnet4.8

      - name: Create Local Docker Image
        run: docker build -t local:aspnet4.8 .

      - name: Run Docker Container
        run: docker run -d --name aspnet4.8 local:aspnet4.8

      - name: List Local Docker Images
        run: docker images

      - name: List Running Containers
        run: docker ps -a
