name: Create EC2 Instance

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID }}
          aws-secret-access-key: ${{ secrets.KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        run: |
          aws ec2 run-instances \
            --image-id ami-12345678 \
            --instance-type t2.micro \
            --key-name your-key-pair \
            --security-group-ids sg-12345678 \
            --subnet-id subnet-12345678 \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=Name,Value=MyInstanceName}]'
        # Replace "MyInstanceName" with the desired name for your instance.
