name: Create EC2 Instance and Install Software

on:
  push:
    branches:
      - testingbranch4

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.ID }}
          aws-secret-access-key: ${{ secrets.KEY }}
          aws-region: us-east-1

      - name: Create EC2 Instance
        id: create-ec2
        run: |
          instance_id=$(aws ec2 run-instances \
            --image-id ami-005f8adf84f8c5057 \
            --instance-type t2.micro \
            --key-name ec2Win2022 \
            --security-group-ids sg-0de8cf629b11c00e5 \
            --subnet-id subnet-03be3039f3ef0ad2c \
            --query 'Instances[0].InstanceId' --output text)
          echo "EC2 instance ID: $instance_id"
          
          # Wait for the EC2 instance to be in the "running" state
          while [[ "$(aws ec2 describe-instances --instance-ids $instance_id --query 'Reservations[0].Instances[0].State.Name' --output text)" != "running" ]]; do
              echo "Waiting for EC2 instance to be in a running state..."
              sleep 150
          done
          
          echo "EC2 instance is now in a running state."


      - name: Configure PowerShell
        run: |
          # Set the execution policy to Unrestricted for the current session
          powershell -ExecutionPolicy Bypass -Command "Set-ExecutionPolicy -Scope Process -ExecutionPolicy Unrestricted"
          # Check PowerShell version
          powershell -Version

      - name: echo '# Download the Git for Windows installer using curl' > install-git.ps1
          echo 'curl -o C:\git-installer.exe -L https://github.com/git-for-windows/git/releases/download/v2.33.1.windows.1/Git-2.33.1-64-bit.exe' >> install-git.ps1
          echo '' >> install-git.ps1
          echo '# Run the installer silently' >> install-git.ps1
          echo 'Start-Process -Wait -FilePath "C:\git-installer.exe" -ArgumentList "/SILENT"' >> install-git.ps1
          echo '' >> install-git.ps1
          echo '# Add Git to the system PATH' >> install-git.ps1
          echo '[System.Environment]::SetEnvironmentVariable("Path", $env:Path + ";C:\Program Files\Git\cmd", [System.EnvironmentVariableTarget]::Machine)' >> install-git.ps1
          echo '' >> install-git.ps1
          echo '# Verify Git installation' >> install-git.ps1
          echo 'git --version' >> install-git.ps1

          powershell -File install-git.ps1

      - name: Verify Git installation
        run: git --version
        
